### ISSUE TITLE
Images -Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by jayo2005** [odoogap/vuestorefront-docker#5]
I tried this on Docker. The Storefront opens but it does not have images. Also on my mobile it syncs all category's but on PC it sync only Men and Women but no images. I cleared the cache on redis but still the same
![2023-07-14_06-41-03](https://github.com/odoogap/vuestorefront-docker/assets/7015925/a77fe7c0-be9b-4703-bc48-539f138041d9)

Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by dduarte-odoogap** [comment]
Try checking on the browser with inspect and check why it's not opening http://localhost:8069/web/image might be some issue with your local
