### ISSUE TITLE
Error During Docker build

### ISSUE THREAD

**Issue by nickchacha** [odoogap/vuestorefront-docker#6]
I'm running into this error at the tail-end vsf container build.  Seems like a dependency lock thing even though it's difficult to figure to go about fixing it

235.8 error execa@9.4.0: The engine "node" is incompatible with this module. Expected version "^18.19.0 || >=20.5.0". Got "20.1.0"

**Comment by dduarte-odoogap** [comment]
You should use node version > 20.10.0

**Comment by nickchacha** [comment]
Thanks @dduarte-odoogap 
Is this the place we're supposed to dictate node version?
```
ARG NODE_VERSION=19.9.0
ARG YARN_VERSION=3.6.1
```
I have tried the above but error still persist. Please asssist
Thanks
